/* Generated by @voxgig/sdkgen. Do not edit. */


const messages = {
  get_info: {
    desc: 'Get information about the GitHub v3 REST SDK.',
  },
}


const sections = {
  intro: {
    path: '../provider/doc/intro.md'
  }
}

const docs = {
  sections,
  messages
}

export default docs


if ('undefined' !== typeof module) {
  module.exports = docs
}
