/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { GithubSDK } = require('@voxgig-sdk/github')

const SdkPkg = require('@voxgig-sdk/github/package.json')


type GithubProviderOptions = {
  // Options passed straight to the GithubSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {pull: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function GithubProvider(this: any, options: GithubProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:github,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'github',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/github',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  // Nested entities cannot build their path without the parent id, so
  // say which key is missing rather than letting the SDK report an opaque
  // 404 on a half-built URL.
  function need_pull_owner(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/github-provider: pull ' + cmd + ': owner is required'
      )
    }
    return value
  }


  function need_pull_repo(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/github-provider: pull ' + cmd + ': repo is required'
      )
    }
    return value
  }


  function need_repo_owner(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/github-provider: repo ' + cmd + ': owner is required'
      )
    }
    return value
  }


  // This API keys a pull by `pull_number`, Seneca by `id`. Carry the
  // API's key across so the Seneca entity has one.
  function id_pull(data: any) {
    if (null != data && null == data.id) {
      data.id = data.pull_number
    }
    return data
  }


  // This API keys a repo by `repo`, Seneca by `id`. Carry the
  // API's key across so the Seneca entity has one.
  function id_repo(data: any) {
    if (null != data && null == data.id) {
      data.id = data.repo
    }
    return data
  }


  const entity: any = {
    pull: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    repo: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

  }


  entity.pull.cmd.list.action =
    async function list_pull(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_pull_owner(q.owner, 'list')
      need_pull_repo(q.repo, 'list')
      const list = await this.shared.sdk.Pull().list(q)
      return list.map((data: any) => entize(id_pull(plain(data))))
    }


  entity.pull.cmd.load.action =
    async function load_pull(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_pull_owner(q.owner, 'load')
      need_pull_repo(q.repo, 'load')
      const res = await ornull(() => this.shared.sdk.Pull().load({ owner: q.owner, pull_number: q.id, repo: q.repo }))
      return null == res ? null : entize(id_pull(plain(res)))
    }


  entity.pull.cmd.save.action =
    async function save_pull(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      need_pull_owner(data.owner, 'save')
      need_pull_repo(data.repo, 'save')

      // This API keys a pull by `pull_number`; Seneca carries it as `id`.
      if (null == data.pull_number && null != data.id) {
        data.pull_number = data.id
      }
      const sdk = this.shared.sdk

      const res = null == data.id
        ? await sdk.Pull().create(data)
        : await sdk.Pull().update(data)

      return entize(id_pull(plain(res)))
    }


  entity.repo.cmd.list.action =
    async function list_repo(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const list = await this.shared.sdk.Repo().list(q)
      return list.map((data: any) => entize(id_repo(plain(data))))
    }


  entity.repo.cmd.load.action =
    async function load_repo(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_repo_owner(q.owner, 'load')
      const res = await ornull(() => this.shared.sdk.Repo().load({ owner: q.owner, repo: q.id }))
      return null == res ? null : entize(id_repo(plain(res)))
    }


  entity.repo.cmd.save.action =
    async function save_repo(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      need_repo_owner(data.owner, 'save')

      // This API keys a repo by `repo`; Seneca carries it as `id`.
      if (null == data.repo && null != data.id) {
        data.repo = data.id
      }
      const sdk = this.shared.sdk

      const res = null == data.id
        ? await sdk.Repo().create(data)
        : await sdk.Repo().update(data)

      return entize(id_repo(plain(res)))
    }


  entity.repo.cmd.remove.action =
    async function remove_repo(this: any, _entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_repo_owner(q.owner, 'remove')
      await ornull(() => this.shared.sdk.Repo().remove({ owner: q.owner, repo: q.id }))
      return null
    }


  entityBuilder(this, {
    provider: {
      name: 'github',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // This API declares no authentication, so no credential is plumbed. The
    // SDK's auth stage emits nothing for an auth-inactive model and deletes
    // any `authorization` header regardless of options, so a keymap lookup
    // here would read a key that could not reach the wire — which is what the
    // first version of this target did.

    this.shared.sdk = options.test
      ? GithubSDK.test(options.testopts || {}, sdkopts)
      : new GithubSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: GithubProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(GithubProvider, { defaults })

export default GithubProvider

if ('undefined' !== typeof module) {
  module.exports = GithubProvider
}
