/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { GithubSDK } = require('@voxgig-sdk/github')

const SdkPkg = require('@voxgig-sdk/github/package.json')


type GithubProviderOptions = {
  // Options passed straight to the GithubSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {pull: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function GithubProvider(this: any, options: GithubProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:github,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'github',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/github',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // `action$` — the directive that selects a custom API action instead of
  // the plain cmd. READ BEFORE cleanq strips it, and still stripped from
  // what reaches the SDK as match fields: it is an instruction to the store,
  // like sort$ and limit$, not a value to filter on.
  //
  // THREE PLACES, because seneca-entity puts it in three places depending on
  // how the caller spelled it, and dropping any one of them silently turns a
  // named action into an ordinary call:
  //
  //   list$/load$/remove$({ action$ })         -> msg.q.action$
  //   ent.directive$({ action$ }).save$()      -> msg.action$
  //   const e = ent.make$({...}); e.action$=.. -> msg.ent.action$
  //
  // `make$({ action$ })` is NOT among them and cannot be: seneca-entity's
  // make$ copies only keys without a `$`, plus the four directives it knows
  // (id$, merge$, custom$, directive$), so an unknown trailing-`$` key is
  // dropped before any store sees it. `id$` reads like the precedent for
  // one, but it works only because make$ names it explicitly. The README
  // says so; there is nothing this plugin can check, because nothing arrives.
  function actionOf(msg: any) {
    const q = msg && msg.q
    const ent = msg && msg.ent

    return null != (q && q.action$) ? q.action$ :
      null != (msg && msg.action$) ? msg.action$ :
        null != (ent && ent.action$) ? ent.action$ :
          undefined
  }


  // The SDK argument for an ACTION on a read cmd: everything the caller sent
  // minus Seneca's own directives, with the record key carried across, plus
  // the `$action` selector the SDK dispatches on.
  //
  // WIDER than the canonical argument on purpose. An action route has its own
  // parameters — GitHub's merge takes commit_title and merge_method, which the
  // canonical PATCH knows nothing about — so narrowing to the plain op's
  // required keys would strip the action's whole payload. The SDK still
  // validates: an action whose own point cannot be built is refused with
  // `point_action_invalid` rather than sent somewhere else.
  function actionq(q: any, rk: string, action: string) {
    const out = cleanq(q)

    if ('id' !== rk && null != out.id) {
      out[rk] = out.id
      delete out.id
    }

    out.$action = action
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  // Nested entities cannot build their path without the parent id, so
  // say which key is missing rather than letting the SDK report an opaque
  // 404 on a half-built URL.
  function need_pull_owner(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/github-provider: pull ' + cmd + ': owner is required'
      )
    }
    return value
  }


  function need_pull_repo(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/github-provider: pull ' + cmd + ': repo is required'
      )
    }
    return value
  }


  function need_repo_owner(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/github-provider: repo ' + cmd + ': owner is required'
      )
    }
    return value
  }


  // This API keys a repo by `repo`, Seneca by `id`. Carry the
  // API's key across so the Seneca entity has one.
  function id_repo(data: any) {
    if (null != data && null == data.id) {
      data.id = data.repo
    }
    return data
  }


  // The custom actions each cmd can reach, as action -> SDK op. An action
  // is an alternative POINT of an ordinary op (`select.$action` in the API
  // model), so `save$` routes by this map rather than assuming update: an
  // action folded into `create` is reached through `save$` too.
  const ACTIONS: Record<string, Record<string, Record<string, string>>> = {
    ["pull"]: {
      list: {},
      load: {},
      save: { ["merge"]: 'update' },
    },
    ["repo"]: {
      list: {},
      load: {},
      save: {},
      remove: {},
    },
  }


  // Resolve an `action$` to the SDK op that serves it, or REFUSE it.
  //
  // Never falls through to the ordinary call. An action name the entity does
  // not have is a caller mistake worth a message that names what is
  // available; performing a plain save instead is the one outcome that must
  // not happen, because it succeeds and does the wrong thing.
  // AN OWN PROPERTY, never an inherited one. `map[name]` resolves
  // `toString`, `constructor`, `valueOf` and the rest off Object's
  // prototype, and each of those is non-null — so the refusal below never
  // fired and the inherited function was handed to the SDK as an op name.
  // That is the silent drop in another hat: the caller named something the
  // entity does not have and was not told. An empty map inherits them all,
  // so a cmd with no actions was the most exposed.
  function actionop(name: string, entname: string, cmd: string) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const map: any = own.call(ents, cmd) ? ents[cmd] : {}
    const op = own.call(map, name) ? map[name] : null

    if (null == op) {
      const valid = Object.keys(map).sort()
      throw new Error(
        '@seneca/github-provider: ' + entname + ' ' + cmd + ': action$ "' + name +
        '" is not an action of this operation. Valid: ' +
        (0 < valid.length ? valid.join(', ') : '(none)'))
    }

    return op
  }


  const entity: any = {
    pull: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    repo: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

  }


  entity.pull.cmd.list.action =
    async function list_pull(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'pull', 'list')
        const found = await this.shared.sdk.Pull()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_pull_owner(q.owner, 'list')
      need_pull_repo(q.repo, 'list')
      const list = await this.shared.sdk.Pull().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.pull.cmd.load.action =
    async function load_pull(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'pull', 'load')
        const hit = await ornull(() => this.shared.sdk.Pull()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      need_pull_owner(q.owner, 'load')
      need_pull_repo(q.repo, 'load')
      const res = await ornull(() => this.shared.sdk.Pull().load({ id: q.id, owner: q.owner, repo: q.repo }))
      return null == res ? null : entize(plain(res))
    }


  entity.pull.cmd.save.action =
    async function save_pull(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'pull', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Pull()[op$](data)
        return entize(plain(done))
      }

      need_pull_owner(data.owner, 'save')
      need_pull_repo(data.repo, 'save')
      const res = null == data.id
        ? await sdk.Pull().create(data)
        : await sdk.Pull().update(data)

      return entize(plain(res))
    }


  entity.repo.cmd.list.action =
    async function list_repo(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'repo', 'list')
        const found = await this.shared.sdk.Repo()[op$](actionq(msg.q, 'repo', action$))
        return found.map((data: any) => entize(id_repo(plain(data))))
      }

      const list = await this.shared.sdk.Repo().list(q)
      return list.map((data: any) => entize(id_repo(plain(data))))
    }


  entity.repo.cmd.load.action =
    async function load_repo(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'repo', 'load')
        const hit = await ornull(() => this.shared.sdk.Repo()[op$](actionq(msg.q, 'repo', action$)))
        return null == hit ? null : entize(id_repo(plain(hit)))
      }

      need_repo_owner(q.owner, 'load')
      const res = await ornull(() => this.shared.sdk.Repo().load({ owner: q.owner, repo: q.id }))
      return null == res ? null : entize(id_repo(plain(res)))
    }


  entity.repo.cmd.save.action =
    async function save_repo(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)

      // This API keys a repo by `repo`; Seneca carries it as `id`.
      if (null == data.repo && null != data.id) {
        data.repo = data.id
      }
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'repo', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Repo()[op$](data)
        return entize(id_repo(plain(done)))
      }

      need_repo_owner(data.owner, 'save')
      const res = null == data.id
        ? await sdk.Repo().create(data)
        : await sdk.Repo().update(data)

      return entize(id_repo(plain(res)))
    }


  entity.repo.cmd.remove.action =
    async function remove_repo(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'repo', 'remove')
        const gone = await ornull(() => this.shared.sdk.Repo()[op$](actionq(msg.q, 'repo', action$)))
        return null == gone ? null : entize(id_repo(plain(gone)))
      }

      need_repo_owner(q.owner, 'remove')
      await ornull(() => this.shared.sdk.Repo().remove({ owner: q.owner, repo: q.id }))
      return null
    }


  entityBuilder(this, {
    provider: {
      name: 'github',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // The provider convention carries credentials, so honour an `apikey`
    // when one is configured and stay quiet when it is not.
    const res = await this.post('sys:provider,get:keymap,provider:github')
    const apikey = res?.keymap?.apikey?.value

    // Hand the credential to the SDK as `apikey`, NOT as an authorization
    // HEADER. The SDK's own auth stage owns that header: it reads
    // `options.apikey`, and on every path where it finds none it DELETES
    // `authorization` before the request goes out. A provider that set the
    // header itself was therefore never authenticated — the SDK stripped the
    // very thing it had just written, on every call, silently. The SDK also
    // owns the scheme prefix, which is resolved from the API definition
    // rather than assumed to be `Bearer`.
    if (null != apikey && '' !== apikey) {
      sdkopts.apikey = apikey
    }

    this.shared.sdk = options.test
      ? GithubSDK.test(options.testopts || {}, sdkopts)
      : new GithubSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: GithubProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(GithubProvider, { defaults })

export default GithubProvider

if ('undefined' !== typeof module) {
  module.exports = GithubProvider
}
