name: "TODO"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
      - name: "todo-to-issue"
        uses: "senecajs/todo-to-issue-action@531d391e061b9770d3d571b70058add5b87c49f1" # master
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "TODO:"
          COMMENT_MARKER: "//"
          INCLUDE_EXT: ".js,.md,.ts"
        id: "todo"
